[tool.poetry]
name = "nzqrc-code"
version = "0.1.0"
description = "Companion code for the book."
authors = ["PhotonicGluon <25820201+PhotonicGluon@users.noreply.github.com>"]
readme = "README.md"
packages = [
    { include = "cleanup" },
    { include = "image_generation" },
    { include = "qr" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"

pillow = "~10.4.0"
typer = "~0.12.5"

[tool.poetry.group.imgen]
optional = true

[tool.poetry.group.imgen.dependencies]
manim = "~0.18.1"
manim-utils = { git = "https://github.com/PhotonicGluon/Manim-Utils.git" }
jupyterlab = "~4.3.0"
jupyterlab-night = "^0.4.6"
notebook = "^7.2.2"
papermill = "~2.6.0"
tqdm = "~4.66.5"

[tool.poetry.group.qr]
optional = true

[tool.poetry.group.qr.dependencies]
qrcode = { extras = ["pil"], version = "~8.0" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
